name: flutter_firebase_nodemcu
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.5.0-138.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^2.31.0
  firebase_database: ^10.5.5
  firebase_auth: ^4.19.6
  flutter_colorpicker: ^1.0.3
  flutter_circle_color_picker: ^0.3.0
  animated_toggle_switch: ^0.8.2
  flutter_blue: ^0.8.0
  cloud_firestore: ^4.17.5
  permission_handler: ^11.3.1
  uuid: ^3.0.4
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  adobe_xd: ^2.0.1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0
  flutter_lints: ^3.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "images/emolink.png"

flutter_native_splash:
  color: "#ffffff"
  image: images/emolink.png
  android: true
  ios: true
  web: true

flutter:
  uses-material-design: true
  assets:
    - images/emolink.png
    - images/bluetooth.png
    - images/gradients.png
